updated scripts

diff --git a/cfjasperreport b/cfjasperreport
--- a/cfjasperreport
+++ b/cfjasperreport
@@ -3,15 +3,52 @@ reldir=`dirname $0`
 cd $reldir/build
 ANTCMD="/bin/sh $HOME/cfdistro/ant/bin/ant -nouserlib -f build.xml"
 export ANT_HOME=$HOME/cfdistro/ant
+CFDISTRO_ZIP=$HOME/cfdistro/cfdistro.zip
+if [ "$HTTP_CLIENT" = "" ]; then
+    if type -p curl >/dev/null 2>&1; then
+        if [ "$https_proxy" != "" ]; then
+            CURL_PROXY="-x $https_proxy"
+        fi
+        HTTP_CLIENT="curl $CURL_PROXY -f -L -o"
+    else
+        HTTP_CLIENT="wget -O"
+    fi
+fi
+if [ ! -d "$ANT_HOME" ]; then
+        export ANT_HOME=/opt/cfdistro/ant
+        ANTCMD="/bin/sh /opt/cfdistro/ant/bin/ant -nouserlib -f build.xml"
+fi
+if [ ! -d "$ANT_HOME" ]; then
+    if [ -r "$CFDISTRO_ZIP" ]; then
+      echo "The zip was already saved to $CFDISTRO_ZIP."
+      echo "If you wish to re-download, delete it."
+      exit 1
+    fi
+    echo "Downloading cfdistro now..."
+    CFDISTRO_DIR=`dirname "$CFDISTRO_ZIP"`
+    mkdir -p "$CFDISTRO_DIR"
+    CFDISTRO_URL="https://github.com/denuno/cfdistro/zipball/master"
+    $HTTP_CLIENT "$CFDISTRO_ZIP" "$CFDISTRO_URL"
+    if [ $? != 0 ]; then
+        echo "Failed to download $CFDISTRO_URL"
+        echo "If you have an old version of libssl you may not have the correct"
+        echo "certificate authority. Either upgrade or set HTTP_CLIENT to insecure:"
+        echo "  export HTTP_CLIENT=\"wget --no-check-certificate -O\" # or"
+        echo "  export HTTP_CLIENT=\"curl --insecure -f -L -o"
+        rm $CFDISTRO_ZIP 2> /dev/null
+        exit 1
+    fi
+	unzip "$CFDISTRO_ZIP" -d "$CFDISTRO_DIR"
+fi
 if [ -z "$1" ]; then
 echo "cfjasperreport control script"
-OPTIONS="start stop help list-targets update exit"
+OPTIONS="build build.all help list-targets update exit"
 select opt in $OPTIONS; do
-if [ "$opt" = "start" ]; then
-	$ANTCMD build.start.launch
+if [ "$opt" = "build" ]; then
+	$ANTCMD build
 	exit
-elif [ "$opt" = "stop" ]; then
-	$ANTCMD server.stop
+elif [ "$opt" = "build.all" ]; then
+	$ANTCMD build.all
 	exit
 elif [ "$opt" = "help" ]; then
 	echo "usage (skips this prompt): cfjasperreport.sh [start|stop|{target}]"
@@ -35,5 +72,3 @@ do
     parameters="$parameters -D$var"
 done
 $ANTCMD $target -Dbasedir=. $parameters
-	
-			
